version: '3.4'

services:
  apigateway:
    image: 10.0.18.30:8082/compuletra.api.gateway
    container_name: gateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    # depends_on:
    #   - consul
      