version: '3.4'

services:
  apigateway:
    image: compuletra/compuletra.api.gateway:latest
    container_name: gateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

networks:
  default:
    external:
      name: compuletra
